name: Setup Node with pnpm cache
description: Common node setup
runs:
  using: "composite"
  steps:
    - name: Set node version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        cache-dependency-path: "**/pnpm-lock.yaml"
inputs:
  node-version:
    required: true

