import vitest from '@vitest/eslint-plugin';
import tseslint from 'typescript-eslint';

export const vitestESLint = tseslint.config({
  files: ['**/*.spec.ts'],
  plugins: {
    vitest
  },
  rules: {
    ...vitest.configs.all.rules,
    'functional/immutable-data': 'off',
    'functional/no-let': 'error',
    '@angular-eslint/no-lifecycle-call': 'error',
    '@typescript-eslint/no-unused-vars': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    '@typescript-eslint/no-empty-function': 'off',
    '@nx/enforce-module-boundaries': [
      'error',
      { enforceBuildableLibDependency: false }
    ],
    'vitest/prefer-lowercase-title': 'error',
    'vitest/max-nested-describe': 'error',
    'vitest/no-focused-tests': 'error',
    'vitest/no-conditional-tests': 'error',
    'vitest/consistent-test-it': 'error',
    'vitest/no-hooks': 'off',
    'vitest/no-restricted-vi-methods': 'error',
    'vitest/consistent-test-filename': [
      'error',
      {
        pattern: '.*.spec.ts'
      }
    ],
    'vitest/max-expects': 'error',
    'vitest/no-alias-methods': 'error',
    'vitest/no-conditional-expect': 'error',
    'vitest/no-conditional-in-test': 'error',
    'vitest/no-disabled-tests': 'error',
    'vitest/no-done-callback': 'error',
    'vitest/no-duplicate-hooks': 'error',
    'vitest/no-large-snapshots': 'error',
    'vitest/no-interpolation-in-snapshots': 'error',
    'vitest/no-mocks-import': 'error',
    'vitest/no-restricted-matchers': 'error',
    'vitest/no-standalone-expect': 'error',
    'vitest/no-test-prefixes': 'error',
    'vitest/no-test-return-statement': 'error',
    'vitest/prefer-called-with': 'error',
    'vitest/prefer-to-be-falsy': 'error',
    'vitest/prefer-to-be-object': 'error',
    'vitest/prefer-to-be-truthy': 'error',
    'vitest/prefer-to-have-length': 'error',
    'vitest/prefer-equality-matcher': 'error',
    'vitest/prefer-strict-equal': 'error',
    'vitest/prefer-expect-resolves': 'error',
    'vitest/prefer-each': 'error',
    'vitest/prefer-hooks-on-top': 'error',
    'vitest/prefer-hooks-in-order': 'error',
    'vitest/prefer-mock-promise-shorthand': 'error',
    'vitest/prefer-vi-mocked': 'error',
    'vitest/prefer-snapshot-hint': 'error',
    'vitest/require-top-level-describe': 'error',
    'vitest/require-to-throw-message': 'error',
    'vitest/require-hook': 'error',
    'vitest/prefer-todo': 'error',
    'vitest/prefer-spy-on': 'error',
    'vitest/prefer-comparison-matcher': 'error',
    'vitest/prefer-to-contain': 'error',
    'vitest/prefer-expect-assertions': 'error',
    'vitest/prefer-to-be': 'error',
    'vitest/padding-around-after-all-blocks': 'error',
    'vitest/padding-around-after-each-blocks': 'error',
    'vitest/padding-around-all': 'error',
    'vitest/padding-around-before-all-blocks': 'error',
    'vitest/padding-around-before-each-blocks': 'error',
    'vitest/padding-around-describe-blocks': 'error',
    'vitest/padding-around-expect-groups': 'error',
    'vitest/padding-around-test-blocks': 'error',
    'vitest/valid-expect-in-promise': 'error',
    'vitest/expect-expect': 'error',
    'vitest/no-identical-title': 'error',
    'vitest/no-commented-out-tests': 'error',
    'vitest/valid-title': 'error',
    'vitest/valid-expect': 'error',
    'vitest/valid-describe-callback': 'error',
    'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
    'vitest/no-import-node-test': 'error'
  }
});
